### PR TITLE
resolves #71

### LINKED ISSUE #71: CG feature docker top
CG to show processes of attacking container to get better visibility what causes high load.

Firstly show all stats:
docker stats --no-stream --no-trunc

Then show processes within offending containers (docker top lg-*).

Wait a max of 5 seconds and kill offenders even if no answer was received.

### PR DESCRIPTION
**Pull request by theaog**
Signed-off-by: aog <theaog@users.noreply.github.com>

### CODE REVIEW

**Review by SkyperTHC — CHANGES_REQUESTED** [review]
If possible please limit each command string to max 255 characters output and do not output more 128 commands per killer container.

Thanks for helping.

**Comment by theaog** [comment]
thank you for the feedback @SkyperTHC, looking into this.

**Comment by theaog** [comment]
resolved max 255 length string and max 128 commands.

the sanitization check was already committed, check line 337

**Review by SkyperTHC — CHANGES_REQUESTED** [review]
Ohh, and sorry to bother you, but can we have the location of the cggroup file as a parameter (and a default if not  parameter is used) such as “-c ‘/sys/fs/cgrup/sf.slice/sf-guest.slce/docker-%s.scope/cgroup.procs’”? The location is different between unix ssytems and if cgroup v1 or v2 is used.

(in Unix C you can easilly subst “%s” in a string but I do not know how to do it in GoLang. In C assuming the string from “-c” in in ‘arg_c_str’ it would be snprintf(buf, sizeof buf, arg_c_str, container_id_string)’

**Comment by theaog** [comment]
what if instead of adding the param we code it in the system to detect the OS and cgroup version to use the correct string?

**Comment by SkyperTHC** [comment]
> what if instead of adding the param we code it in the system to detect the OS and cgroup version to use the correct string?
> 
> for one it's more fun, I prefer automation over manual settings, also as CG runs in a container via compose config it removes the burden for the user to modify the compose file depending on the system they use.
> 
> what do you think?

Sounds good but there should also be an option to overwrite it just in case it changes (The directory is defined by docker and they do not guarantee to keep it named like that. It will also change when we add more slices to the cgroups...so auto-detect is great but need an option just in case....)

**Comment by theaog** [comment]
oki doki I'll add a flag for that string

**Review by SkyperTHC — APPROVED** [review]

**Pull request merged**
